# active spring boot profile
spring:
   profiles:
      active: dev

---

# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB

---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
   # datasource
   datasource:
      username: spring
      password: spring
      driver-class-name: org.mariadb.jdbc.Driver

      url: jdbc:mysql://34.64.73.89:3306/spring?characterEncoding=utf8&allowMultiQueries=true

      hikari:
         minimum-idle: 100
         maximum-pool-size: 200

---

# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource:
      username: webdb
      password: blahblha#!@0909#@!
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://34.64.73.89:3306/spring?characterEncoding=utf8
      hikari:
         minimum-idle: 100
         maximum-pool-size: 200

---

# server
server:
   port: 7777
   servlet:
     context-path: /
     encoding:
        charset: utf-8
        enabled: true
        force: false
        force-request: false
        force-response: false

---

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

